import { computed } from 'vue'
import { locale } from '../composables/useLanguage'

const shared = [
  { id: 'sihui-mao', photo: 'mentors/photos/Sihui_Mao.jpg' },
  { id: 'xinyi-li', photo: 'mentors/photos/Xinyi_Li.jpg' },
  { id: 'tianhua-zhao', photo: 'mentors/photos/Tianhua_Zhao.jpg' },
  { id: 'jiayi-he', photo: 'mentors/photos/Jiayi_He.jpg' },
  { id: 'cong-liu', photo: 'mentors/photos/test_mentorphoto.png' },
]
const profiles = {
  en: [
    { name: 'Sihui Mao', role: 'G2 PhD Student, BBS (TMMPP Track) · Yale University', photoAlt: 'Profile portrait of Sihui Mao', research: 'Cell Biology · Cellular & Molecular Physiology · Metabolism · Neurology · Biochemistry', areas: 'General Application Questions · CV · SOP · PS · Interview', bio: 'I graduated from Zhili College at Tsinghua University, where I developed my interest in cellular metabolism and physiology. I am now pursuing my PhD at Yale, studying mitochondrial function in neuronal and glial cells using iPSC models.', experience: 'I worked as a writing assistant at the Tsinghua Writing Center for two years, where I gained experience in helping students organize their ideas, build clear narratives, and communicate scientific messages effectively. I continued to strengthen these skills at Yale through specialized training in scientific writing. I have mentored over five students through their graduate school applications so far and I really enjoy exchanging ideas, learning and growing together with students throughout the process.', availability: 'General Application Questions · CV · SOP · PS · Interview' },
    { name: 'Xinyi Li', role: 'G2 PhD Student, Biology · Carnegie Mellon University', photoAlt: 'Profile portrait of Xinyi Li', research: 'Computational Biology · Evolutionary Biology · Comparative Genomics · Molecular Biology', areas: 'General Application Questions · CV · Interviews · SOP', bio: 'I graduated from the School of Life Sciences at Tsinghua University and am currently a PhD student in Biological Sciences at Carnegie Mellon University. My current research focuses on using comparative genomics to understand the genetic mechanisms underlying vertebrate evolution. During my undergraduate studies, my research experience also covered developmental biology (stem cells and embryo models, morphogenesis during early cnidarian development) and synthetic biology (Tsinghua iGEM 2023).', experience: 'I hope my experiences across different research areas and the graduate application process can be helpful to others, and I’m happy to share what I’ve learned along the way.', availability: 'General Application Questions · CV · Interviews · SOP' },
    { name: 'Tianhua Zhao', role: 'G2 PhD Student, Biology · Caltech', photoAlt: 'Profile portrait of Tianhua Zhao', research: 'Synthetic Biology · Developmental Biology · Bioengineering', areas: 'General Application Questions · CV · Interview · SOP', bio: 'I graduated from the School of Life Sciences at Tsinghua University, where I had the opportunity to explore interdisciplinary research. I’m now pursuing my graduate studies at the California Institute of Technology.', experience: 'I’d be happy to share what I’ve learned along the way and hopefully help with any questions you may have about the application process!', availability: 'General Application Questions · CV · Interview · SOP' },
    { name: 'Jiayi He', role: 'G2 PhD Student, Biology · MIT', photoAlt: 'Profile portrait of Jiayi He', research: 'Molecular and Cellular Biology · Genetics & Epigenetics · Gene Regulation', areas: 'General Application Questions · CV · Interview · SOP', bio: 'I graduated from Zhili College at Tsinghua University with a major in Biology. My undergraduate research used C. elegans as a model organism to study how environmental factors affect the nervous system, with forward genetic screening and transcriptomic analysis as my main approaches. I carried my interest in gene regulation and stress response into graduate school, and I’m now focused on leveraging high-throughput phenotypic screening to understand various aspects of cell biology, with a particular emphasis on cellular stress response.', experience: 'I’ve been a mentor in the MIT Biology Application Assistance Program (BAAP), where I found it deeply rewarding to help applicants navigate the process. I’d be happy to share my own experience with grad school applications and answer any questions you have!', availability: 'General Application Questions · CV · Interview · SOP' },
    
    { name: 'Cong Liu', role: 'G3 PhD Student, Metabolism and Nutrient Biology · Columbia University', photoAlt: 'Placeholder portrait for Cong Liu', research: 'Metabolism · Molecular and Cellular Biology · Cancer Biology · Epigenetics · Biochemistry', areas: 'General Application Questions · CV · SOP · Interview', bio: 'I graduated from the School of Life Sciences at Tsinghua University and am now a PhD candidate in the Metabolism and Nutrient Biology track at Columbia University Irving Medical Center. Back in undergrad, I studied cellular metabolism and the key roles of mitochondria in cell proliferation. Building on my interest in metabolism, I’m now exploring how metabolism affects epigenetics and cell fate, and how these interactions contribute to cancer progression.', experience: 'I’ve been incredibly lucky to get so much support along the way with grad school applications and my research journey, and I’d love to pass it on! If you ever want to chat about grad school applications, research, life as a grad student, or just anything on your mind, come say hi anytime :)', availability: 'General Application Questions · CV · SOP · Interview' },
  ],
  zh: [
    { name: '毛斯慧', role: 'BBS（TMMPP 方向）博士二年级 · 耶鲁大学', photoAlt: 'Sihui Mao 的个人照片', research: '细胞生物学 · 细胞与分子生理学 · 代谢 · 神经学 · 生物化学', areas: '申请综合问题 · 简历 · SOP · 个人陈述 · 面试', bio: '我本科毕业于清华大学致理书院，并在这期间逐渐培养了对细胞代谢与生理学的浓厚兴趣。目前，我正在耶鲁大学攻读博士学位，研究方向为利用 iPSC 模型研究神经元和胶质细胞中的线粒体功能。', experience: '本科期间，我曾在清华大学写作中心担任两年写作助理，积累了帮助同学梳理思路、搭建清晰叙事框架、以及更准确有效地传达科学信息的经验。进入耶鲁大学后，我也通过系统的科学写作训练，进一步提升了自己科研写作与沟通能力。迄今为止，我已经帮助五名以上的同学准备和完成研究生申请。在这个过程中，我尤其享受与同学们一起交流想法、梳理兴趣与目标，并在彼此的分享和讨论中共同学习、共同成长。', availability: '申请综合问题 · 简历 · 学术目的陈述 · 个人陈述 · 面试' },
    { name: '李昕仪', role: '生物学博士二年级 · 卡内基梅隆大学', photoAlt: 'Xinyi Li 的个人照片', research: '计算生物学 · 进化生物学 · 比较基因组学 · 分子生物学', areas: '申请综合问题 · 简历 · 面试 · SOP', bio: '我本科毕业于清华大学生命科学学院，目前在卡内基梅隆大学攻读生物科学博士学位。现阶段的研究主要利用比较基因组学方法，探索脊椎动物进化背后的遗传机制。本科期间，我的科研经历还涉及发育生物学（干细胞与胚胎模型，以及刺胞动物早期发育中的形态发生）和合成生物学（清华大学 iGEM 2023）。', experience: '希望我在不同研究领域和研究生申请过程中的经历能够为大家提供帮助，也很乐意分享自己一路所学。', availability: '申请综合问题 · 简历 · 面试 · 学术目的陈述' },
    { name: '赵天骅', role: '生物学博士二年级 · 加州理工学院', photoAlt: 'Tianhua Zhao 的个人照片', research: '合成生物学 · 发育生物学 · 生物工程', areas: '申请综合问题 · 简历 · 面试 · SOP', bio: '我毕业于清华大学生命科学学院，并有幸在本科期间接触并探索了不同方向的跨学科研究。毕业后，我来到加州理工学院继续深造，目前正在攻读研究生学位。', experience: '一路走来，我也经历过许多关于科研方向、研究生申请和未来选择的探索与思考。我很乐意和大家分享自己的经历与体会，也希望能尽力帮助大家解答申请过程中遇到的问题，陪大家一起把想法理清、把适合自己的道路慢慢找到。', availability: '申请综合问题 · 简历 · 面试 · 学术目的陈述' },
    { name: '何嘉艺', role: '生物学博士二年级 · 麻省理工学院', photoAlt: 'Jiayi He 的个人照片', research: '分子与细胞生物学 · 遗传学与表观遗传学 · 基因调控', areas: '申请综合问题 · 简历 · 面试 · SOP', bio: '我本科毕业于清华大学致理书院生物科学专业。本科期间，我以秀丽隐杆线虫为模式生物，研究环境因素如何影响神经系统，主要采用正向遗传筛选和转录组分析方法。进入研究生阶段后，我延续了对基因调控和应激反应的兴趣，目前专注于利用高通量表型筛选研究细胞生物学的多个方面，尤其关注细胞应激反应。', experience: '我曾担任麻省理工学院生物学申请援助项目（BAAP）的志愿者，并从中感受到帮助申请者顺利完成申请过程是一件非常有意义的事。我很乐意分享自己的研究生申请经验，并回答大家的任何问题！', availability: '申请综合问题 · 简历 · 面试 · 学术目的陈述' },
    { name: '刘悰', role: '代谢与营养生物学博士三年级 · 哥伦比亚大学', photoAlt: '刘悰的示例照片', research: '代谢 · 分子与细胞生物学 · 肿瘤生物学 · 表观遗传学 · 生物化学', areas: '申请综合问题 · 简历 · SOP · 面试', bio: '我本科毕业于清华大学生命科学学院，目前在哥伦比亚大学欧文医学中心攻读代谢与营养生物学方向的博士学位。本科期间，我研究细胞代谢以及线粒体在细胞增殖中的关键作用。延续对代谢的兴趣，我现在正在探索代谢如何影响表观遗传与细胞命运，以及这些相互作用如何推动癌症进展。', experience: '在研究生申请和科研的道路上，我非常幸运地得到了许多支持，也希望把这份帮助传递下去！无论你想聊研究生申请、科研、研究生生活，还是任何心事，都欢迎随时来找我交流 :)', availability: '申请综合问题 · 简历 · 学术目的陈述 · 面试' },
  ],
}

export const mentorProfiles = computed(() =>
  profiles[locale.value].map((profile, index) => ({ ...shared[index], ...profile })),
)
