import { computed } from 'vue'
import { locale } from '../composables/useLanguage'

const shared = [
  { id: 'tianhua-zhao', photo: 'mentors/photos/test_mentorphoto.png' },
  { id: 'jiayi-he', photo: 'mentors/photos/test_mentorphoto.png' },
  { id: 'sihui-mao', photo: 'mentors/photos/test_mentorphoto.png' },
  { id: 'xinyi-li', photo: 'mentors/photos/test_mentorphoto.png' },
]

const profiles = {
  en: [
    { name: 'Tianhua Zhao', role: 'G2 PhD Student, Biology · Caltech', photoAlt: 'Profile portrait of Tianhua Zhao', research: 'Synthetic Biology · Developmental Biology · Bioengineering', areas: 'General Application Questions · CV · Interview · SOP', bio: 'I graduated from the School of Life Sciences at Tsinghua University, where I had the opportunity to explore interdisciplinary research. I’m now pursuing my graduate studies at the California Institute of Technology.', experience: 'I’d be happy to share what I’ve learned along the way and hopefully help with any questions you may have about the application process ：）', availability: 'General Application Questions · CV · Interview · SOP' },
    { name: 'Jiayi He', role: 'G2 PhD Student, Biology · MIT', photoAlt: 'Profile portrait of Jiayi He', research: 'Molecular and Cellular Biology · Genetics & Epigenetics · Gene Regulation', areas: 'General Application Questions · CV · Interview · SOP', bio: 'I graduated from Zhili College at Tsinghua University with a major in Biology. My undergraduate research used C. elegans as a model organism to study how environmental factors affect the nervous system, with forward genetic screening and transcriptomic analysis as my main approaches. I carried my interest in gene regulation and stress response into graduate school, and I’m now focused on leveraging high-throughput phenotypic screening to understand various aspects of cell biology, with a particular emphasis on cellular stress response.', experience: 'I’ve been a mentor in the MIT Biology Application Assistance Program (BAAP), where I found it deeply rewarding to help applicants navigate the process. I’d be happy to share my own experience with grad school applications and answer any questions you have!', availability: 'General Application Questions · CV · Interview · SOP' },
    { name: 'Sihui Mao', role: 'G2 PhD Student, BBS (TMMPP Track) · Yale University', photoAlt: 'Profile portrait of Sihui Mao', research: 'Cell Biology · Cellular & Molecular Physiology · Metabolism · Neurology · Biochemistry', areas: 'General Application Questions · CV · SOP · PS · Interview', bio: 'I graduated from Zhili College at Tsinghua University, where I developed my interest in cellular metabolism and physiology. I am now pursuing my PhD at Yale, studying mitochondrial function in neuronal and glial cells using iPSC models.', experience: 'I worked as a writing assistant at the Tsinghua Writing Center for two years, where I gained experience in helping students organize their ideas, build clear narratives, and communicate scientific messages effectively. I continued to strengthen these skills at Yale through specialized training in scientific writing. I have mentored more than five students through their graduate school applications so far and I really enjoy exchanging ideas, learning and growing together with students throughout the process.', availability: 'General Application Questions · CV · SOP · PS · Interview' },
    { name: 'Xinyi Li', role: 'G2 PhD Student, Biology · Carnegie Mellon University', photoAlt: 'Profile portrait of Xinyi Li', research: 'Computational Biology · Evolutionary Biology · Comparative Genomics · Molecular Biology', areas: 'General Application Questions · CV · Interviews · SOP', bio: 'I graduated from the School of Life Sciences at Tsinghua University and am currently a PhD student in Biological Sciences at Carnegie Mellon University. My current research focuses on using comparative genomics to understand the genetic mechanisms underlying vertebrate evolution. During my undergraduate studies, my research experience also covered developmental biology (stem cells and embryo models, morphogenesis during early cnidarian development) and synthetic biology (Tsinghua iGEM 2023).', experience: 'I hope my experiences across different research areas and the graduate application process can be helpful to others, and I’m happy to share what I’ve learned along the way.', availability: 'General Application Questions · CV · Interviews · SOP' },
  ],
  zh: [
    { name: 'Tianhua Zhao', role: '生物学博士二年级 · 加州理工学院', photoAlt: 'Tianhua Zhao 的个人照片', research: '合成生物学 · 发育生物学 · 生物工程', areas: '申请综合问题 · 简历 · 面试 · 学术目的陈述', bio: '我本科毕业于清华大学生命科学学院，在那里有机会探索跨学科研究。目前，我正在加州理工学院攻读研究生学位。', experience: '我很乐意分享自己一路走来的经验，也希望能帮助大家解答申请过程中遇到的任何问题 ：）', availability: '申请综合问题 · 简历 · 面试 · 学术目的陈述' },
    { name: 'Jiayi He', role: '生物学博士二年级 · 麻省理工学院', photoAlt: 'Jiayi He 的个人照片', research: '分子与细胞生物学 · 遗传学与表观遗传学 · 基因调控', areas: '申请综合问题 · 简历 · 面试 · 学术目的陈述', bio: '我本科毕业于清华大学致理书院生物科学专业。本科期间，我以秀丽隐杆线虫为模式生物，研究环境因素如何影响神经系统，主要采用正向遗传筛选和转录组分析方法。进入研究生阶段后，我延续了对基因调控和应激反应的兴趣，目前专注于利用高通量表型筛选研究细胞生物学的多个方面，尤其关注细胞应激反应。', experience: '我曾担任麻省理工学院生物学申请援助项目（BAAP）的导师，并深切感受到帮助申请者顺利完成申请过程是一件非常有意义的事。我很乐意分享自己的研究生申请经验，并回答大家的任何问题！', availability: '申请综合问题 · 简历 · 面试 · 学术目的陈述' },
    { name: 'Sihui Mao', role: 'BBS（TMMPP 方向）博士二年级 · 耶鲁大学', photoAlt: 'Sihui Mao 的个人照片', research: '细胞生物学 · 细胞与分子生理学 · 代谢 · 神经学 · 生物化学', areas: '申请综合问题 · 简历 · 学术目的陈述 · 个人陈述 · 面试', bio: '我本科毕业于清华大学致理书院，并在那里培养了对细胞代谢和生理学的兴趣。目前，我正在耶鲁大学攻读博士学位，利用 iPSC 模型研究神经元和胶质细胞中的线粒体功能。', experience: '我曾在清华大学写作中心担任两年写作助理，积累了帮助学生组织思路、构建清晰叙事并有效传达科学信息的经验。进入耶鲁大学后，我通过专门的科学写作训练进一步提升了这些能力。迄今为止，我已经指导了五名以上学生完成研究生申请，也非常享受在这一过程中与学生交流想法、相互学习和共同成长。', availability: '申请综合问题 · 简历 · 学术目的陈述 · 个人陈述 · 面试' },
    { name: 'Xinyi Li', role: '生物学博士二年级 · 卡内基梅隆大学', photoAlt: 'Xinyi Li 的个人照片', research: '计算生物学 · 进化生物学 · 比较基因组学 · 分子生物学', areas: '申请综合问题 · 简历 · 面试 · 学术目的陈述', bio: '我本科毕业于清华大学生命科学学院，目前在卡内基梅隆大学攻读生物科学博士学位。现阶段的研究主要利用比较基因组学方法，探索脊椎动物进化背后的遗传机制。本科期间，我的科研经历还涉及发育生物学（干细胞与胚胎模型，以及刺胞动物早期发育中的形态发生）和合成生物学（清华大学 iGEM 2023）。', experience: '希望我在不同研究领域和研究生申请过程中的经历能够为大家提供帮助，也很乐意分享自己一路所学。', availability: '申请综合问题 · 简历 · 面试 · 学术目的陈述' },
  ],
}

export const mentorProfiles = computed(() =>
  profiles[locale.value].map((profile, index) => ({ ...shared[index], ...profile })),
)
